baseURL = "http://takemusu-aiki.club/docdock/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "Информационный портал клуба"
theme = "docdock"
themesdir = "themes"

[params]
#editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
unfoldedMenus = ["clubinfo"] # set menu identifiers which should be displayed unfolded  
themeVariant = "blue" # choose theme variant "green", "gold" , "blue" (default)


[outputs]
home = [ "HTML", "RSS", "JSON"]


#[[menu.shortcuts]]
#pre = "<h3>Дополнительно</h3>"
#name = "<i class='fa fa-github'></i> Github repo"
#identifier = "ds"
#url = "https://github.com/vjeantet/hugo-theme-docdock"
#weight = 1

#[[menu.shortcuts]]
#name = "<i class='fa fa-bookmark'></i> Hugo Documentation"
#identifier = "hugodoc"
#url = "https://gohugo.io/"
#weight = 2

#[[menu.shortcuts]]
#name = "<i class='fa fa-bullhorn'></i> Credits"
#url = "/credits"
#weight = 3